import Foundation

/// Resolves the label shown for an account. Mirrors `src/Windows/Model/AccountLabel.cs`.
///
/// **Every label comes from the user's own Anthropic data — nothing about any organisation is
/// hardcoded** (docs/multi-account.md, "Labels").
public enum AccountLabel {

    /// The ladder, in order:
    ///  1. the user's own override from `accounts.json`
    ///  2. `oauthAccount.organizationName`, **unless** it is Anthropic's auto-generated name for a
    ///     personal organisation, `<emailAddress>'s Organization` — a poor label, so it falls through
    ///  3. the plan from `subscription_type`, title-cased ("Max", "Team", "Enterprise")
    ///  4. the local part of `emailAddress`
    ///  5. "Konto N"
    public static func resolve(
        override: String?,
        identity: AccountIdentity?,
        subscriptionType: String?,
        slotNumber: Int
    ) -> String {
        if let override, !override.trimmingCharacters(in: .whitespaces).isEmpty {
            return override.trimmingCharacters(in: .whitespaces)
        }
        if let name = identity?.organizationName, !name.isEmpty,
           !isAutoGeneratedPersonalOrganisation(name: name, email: identity?.emailAddress) {
            return name
        }
        if let plan = subscriptionType?.trimmingCharacters(in: .whitespaces), !plan.isEmpty {
            return plan.prefix(1).uppercased() + plan.dropFirst().lowercased()
        }
        if let email = identity?.emailAddress, let local = email.split(separator: "@").first, !local.isEmpty {
            return String(local)
        }
        return "Konto \(slotNumber)"
    }

    /// Observed on a real personal Max login: `alex@example.com's Organization`. Anthropic
    /// generates it for a personal organisation, and it is a poor menu-bar label.
    public static func isAutoGeneratedPersonalOrganisation(name: String, email: String?) -> Bool {
        guard let email, !email.isEmpty else { return false }
        return name == "\(email)'s Organization"
    }

    /// Two accounts must never present the same label. If they collide, append the plan; if they
    /// still collide, append the email local part.
    public static func disambiguate(
        _ labels: [String],
        plans: [String?],
        emails: [String?]
    ) -> [String] {
        var result = labels
        func hasDuplicates(_ values: [String]) -> Bool { Set(values).count != values.count }

        if hasDuplicates(result) {
            var counts: [String: Int] = [:]
            for label in result { counts[label, default: 0] += 1 }
            for index in result.indices where (counts[result[index]] ?? 0) > 1 {
                if let plan = plans[index], !plan.isEmpty {
                    result[index] = "\(result[index]) (\(plan.prefix(1).uppercased() + plan.dropFirst().lowercased()))"
                }
            }
        }
        if hasDuplicates(result) {
            var counts: [String: Int] = [:]
            for label in result { counts[label, default: 0] += 1 }
            for index in result.indices where (counts[result[index]] ?? 0) > 1 {
                if let email = emails[index], let local = email.split(separator: "@").first {
                    result[index] = "\(result[index]) · \(local)"
                }
            }
        }
        return result
    }
}

public extension String {
    /// `nil` for an empty or whitespace-only string, so an override of `""` falls through the
    /// ladder rather than presenting as a blank label.
    var nilIfEmpty: String? {
        let trimmed = trimmingCharacters(in: .whitespaces)
        return trimmed.isEmpty ? nil : trimmed
    }
}
