using ClaudeStatusBar.Data;
using ClaudeStatusBar.Model;
using Xunit;

namespace ClaudeStatusBar.Tests;

/// <summary>
/// docs/multi-account.md "Labels": override -> organizationName -> plan (title-cased) ->
/// email local part -> "Konto N", then a whole-set disambiguation pass for duplicates.
/// </summary>
public class AccountLabelTests
{
    static AccountIdentity Identity(string? orgName = null, string? email = null) => new(
        AccountUuid: "uuid-" + Guid.NewGuid().ToString("N")[..8],
        OrganizationUuid: null,
        OrganizationName: orgName,
        OrganizationType: null,
        SeatTier: null,
        BillingType: null,
        EmailAddress: email,
        DisplayName: null);

    [Fact]
    public void Resolve_Step1_OverrideWins_EvenWhenEverythingElsePresent()
    {
        var input = new AccountLabelInput("My Custom Label", Identity("Acme", "alice@example.com"), "max");
        Assert.Equal("My Custom Label", AccountLabel.Resolve(input, 0));
    }

    [Fact]
    public void Resolve_Step2_OrganizationName_WhenNoOverride()
    {
        var input = new AccountLabelInput(null, Identity("Acme Corp", "alice@example.com"), "max");
        Assert.Equal("Acme Corp", AccountLabel.Resolve(input, 0));
    }

    /// <summary>
    /// docs/multi-account.md "Labels": Anthropic auto-generates "&lt;email&gt;'s Organization" for a
    /// personal (non-Team/Enterprise) org -- observed on this machine's real personal Max login.
    /// That name is a poor tray label, so it must be skipped in favour of the plan name, never
    /// hardcoded to any particular email or plan string.
    /// </summary>
    [Fact]
    public void Resolve_AutoGeneratedPersonalOrgName_PrefersPlanOverTheOrgName()
    {
        var input = new AccountLabelInput(null, Identity("alex@example.com's Organization", "alex@example.com"), "max");
        Assert.Equal("Max", AccountLabel.Resolve(input, 0));
    }

    [Fact]
    public void Resolve_AutoGeneratedPersonalOrgName_NoPlanAvailable_FallsThroughToEmailLocalPart()
    {
        var input = new AccountLabelInput(null, Identity("alice@example.com's Organization", "alice@example.com"), SubscriptionType: null);
        Assert.Equal("alice", AccountLabel.Resolve(input, 0));
    }

    [Fact]
    public void Resolve_RealOrganizationName_IsUsedAsIs_EvenWithApostropheS()
    {
        // A real org name that happens to end in "'s Team" (not "'s Organization") must not be
        // mistaken for the auto-generated pattern.
        var input = new AccountLabelInput(null, Identity("Bob's Team", "bob@example.com"), "team");
        Assert.Equal("Bob's Team", AccountLabel.Resolve(input, 0));
    }

    [Theory]
    [InlineData("alex@example.com's Organization", true)]
    [InlineData("Acme AB", false)]
    [InlineData("Bob's Team", false)]
    public void IsAutoGeneratedPersonalOrgName_MatchesOnlyTheAnthropicPattern(string orgName, bool expected)
    {
        Assert.Equal(expected, AccountLabel.IsAutoGeneratedPersonalOrgName(orgName));
    }

    /// <summary>The task's own live scenario: a Team login and a personal Max login for the same person -- "Acme AB" and "Max", derived purely from the data.</summary>
    [Fact]
    public void Disambiguate_TeamOrgAndAutoGeneratedPersonalOrg_ProduceOrgNameAndPlanName()
    {
        var accounts = new[]
        {
            new AccountLabelInput(null, Identity("Acme AB", "alex@example.com"), "team"),
            new AccountLabelInput(null, Identity("alex@example.com's Organization", "alex@example.com"), "max"),
        };

        IReadOnlyList<string> labels = AccountLabel.Disambiguate(accounts);

        Assert.Equal("Acme AB", labels[0]);
        Assert.Equal("Max", labels[1]);
    }

    [Fact]
    public void Resolve_Step3_PlanFromSubscriptionType_WhenNoOverrideOrOrgName()
    {
        var input = new AccountLabelInput(null, Identity(orgName: null, email: "alice@example.com"), "max");
        Assert.Equal("Max", AccountLabel.Resolve(input, 0));
    }

    [Fact]
    public void Resolve_Step4_EmailLocalPart_WhenNoOverrideOrgNameOrPlan()
    {
        var input = new AccountLabelInput(null, Identity(orgName: null, email: "alice@example.com"), SubscriptionType: null);
        Assert.Equal("alice", AccountLabel.Resolve(input, 0));
    }

    [Fact]
    public void Resolve_Step5_KontoN_WhenNothingElseAvailable()
    {
        var input = new AccountLabelInput(null, null, null);
        Assert.Equal("Konto 1", AccountLabel.Resolve(input, 0));
        Assert.Equal("Konto 3", AccountLabel.Resolve(input, 2));
    }

    [Theory]
    [InlineData("max", "Max")]
    [InlineData("team", "Team")]
    [InlineData("enterprise", "Enterprise")]
    [InlineData("MAX", "Max")]
    public void TitleCasePlan_TitleCasesEveryKnownPlan(string raw, string expected)
    {
        Assert.Equal(expected, AccountLabel.TitleCasePlan(raw));
    }

    [Fact]
    public void Disambiguate_TwoAccounts_SameOrganizationName_DifferentPlan_AppendsPlan()
    {
        var accounts = new[]
        {
            new AccountLabelInput(null, Identity("Acme", "alice@example.com"), "max"),
            new AccountLabelInput(null, Identity("Acme", "bob@example.com"), "team"),
        };

        IReadOnlyList<string> labels = AccountLabel.Disambiguate(accounts);

        Assert.Equal("Acme (Max)", labels[0]);
        Assert.Equal("Acme (Team)", labels[1]);
    }

    [Fact]
    public void Disambiguate_ThreeAccounts_SameOrganizationNameAndPlan_DisambiguatedByEmailLocalPart()
    {
        var accounts = new[]
        {
            new AccountLabelInput(null, Identity("Acme", "alice@example.com"), "team"),
            new AccountLabelInput(null, Identity("Acme", "bob@example.com"), "team"),
            new AccountLabelInput(null, Identity("Acme", "carol@example.com"), "team"),
        };

        IReadOnlyList<string> labels = AccountLabel.Disambiguate(accounts);

        Assert.Equal("Acme (Team, alice)", labels[0]);
        Assert.Equal("Acme (Team, bob)", labels[1]);
        Assert.Equal("Acme (Team, carol)", labels[2]);
        Assert.Equal(3, labels.Distinct().Count());
    }

    [Fact]
    public void Disambiguate_UniqueBaseLabels_ReturnedUnchanged()
    {
        var accounts = new[]
        {
            new AccountLabelInput(null, Identity("Acme"), "max"),
            new AccountLabelInput(null, Identity("Globex"), "team"),
        };

        IReadOnlyList<string> labels = AccountLabel.Disambiguate(accounts);

        Assert.Equal("Acme", labels[0]);
        Assert.Equal("Globex", labels[1]);
    }

    [Fact]
    public void Disambiguate_TwoAutoGeneratedPersonalOrgNames_SamePlan_DisambiguatedByEmailLocalPart()
    {
        var accounts = new[]
        {
            new AccountLabelInput(null, Identity("alice@example.com's Organization", "alice@example.com"), "max"),
            new AccountLabelInput(null, Identity("bob@example.com's Organization", "bob@example.com"), "max"),
        };

        IReadOnlyList<string> labels = AccountLabel.Disambiguate(accounts);

        Assert.Equal("Max (Max, alice)", labels[0]);
        Assert.Equal("Max (Max, bob)", labels[1]);
    }

    [Fact]
    public void Disambiguate_SingleAccount_ReturnsBaseLabel()
    {
        var accounts = new[] { new AccountLabelInput(null, Identity("Acme"), "max") };
        Assert.Equal(new[] { "Acme" }, AccountLabel.Disambiguate(accounts));
    }

    /// <summary>
    /// docs/multi-account.md "Duplicate accounts": a true duplicate (same AccountIdentity.
    /// StateKey, see Model/AccountDuplicates.cs) must never be treated as a DIFFERENT account
    /// that happens to share a label -- its collision with the account it duplicates must not
    /// force either one into the "(plan)"/"(plan, email)" suffixing this pass exists for.
    /// </summary>
    [Fact]
    public void Disambiguate_TrueDuplicate_ExcludedFromCollisionCounting_KeptAccountLabelStaysPlain()
    {
        var accounts = new[]
        {
            new AccountLabelInput(null, Identity(orgName: null, email: "alex@example.com"), "max"),
            new AccountLabelInput(null, Identity(orgName: null, email: "alex@example.com"), "max"),
        };
        var isDuplicate = new[] { false, true };

        IReadOnlyList<string> labels = AccountLabel.Disambiguate(accounts, isDuplicate);

        // Without the duplicate flag this would come back "Max (Max, alex)" for both (three
        // colliding accounts' worth of suffixing logic firing for what is really only one) --
        // the real symptom docs/multi-account.md's live scenario hit. With it, the kept account
        // (index 0) is never told it collides with anything, so it keeps its plain base label.
        Assert.Equal("Max", labels[0]);
    }

    /// <summary>A THIRD, genuinely different account sharing the kept account's label must still be disambiguated normally -- the duplicate flag only exempts the duplicate pair from each other, not the whole set from disambiguation.</summary>
    [Fact]
    public void Disambiguate_TrueDuplicate_DoesNotSuppressDisambiguationAgainstAGenuinelyDifferentThirdAccount()
    {
        var accounts = new[]
        {
            new AccountLabelInput(null, Identity(orgName: null, email: "alex@example.com"), "max"),
            new AccountLabelInput(null, Identity(orgName: null, email: "alex@example.com"), "max"), // duplicate of [0]
            new AccountLabelInput(null, Identity(orgName: null, email: "bob@example.com"), "max"),  // genuinely different Max account
        };
        var isDuplicate = new[] { false, true, false };

        IReadOnlyList<string> labels = AccountLabel.Disambiguate(accounts, isDuplicate);

        Assert.Equal("Max (Max, alex)", labels[0]);
        Assert.Equal("Max (Max, bob)", labels[2]);
    }

    // ---- email domain as the first disambiguator (docs/multi-account.md "Labels") ----

    [Fact]
    public void Disambiguate_SamePlan_DifferentEmailDomains_AppendsTheDomain_BeforeThePlanOrLocalPart()
    {
        var accounts = new[]
        {
            new AccountLabelInput(null, Identity(email: "alex@example.com"), "max"),
            new AccountLabelInput(null, Identity(email: "alex@example.org"), "max"),
        };

        IReadOnlyList<string> labels = AccountLabel.Disambiguate(accounts);

        Assert.Equal("Max (example.com)", labels[0]);
        Assert.Equal("Max (example.org)", labels[1]);
    }

    [Fact]
    public void Disambiguate_Domain_IsComparedCaseInsensitively_AndShownLowerCase()
    {
        var accounts = new[]
        {
            new AccountLabelInput(null, Identity(email: "Alex@Example.COM"), "max"),
            new AccountLabelInput(null, Identity(email: "bob@example.org"), "max"),
        };

        IReadOnlyList<string> labels = AccountLabel.Disambiguate(accounts);

        Assert.Equal("Max (example.com)", labels[0]);
        Assert.Equal("Max (example.org)", labels[1]);
    }

    [Fact]
    public void Disambiguate_SameEmailDomain_FallsBackToThePlanAndLocalPartSteps_AsBefore()
    {
        var accounts = new[]
        {
            new AccountLabelInput(null, Identity(email: "alice@example.com"), "max"),
            new AccountLabelInput(null, Identity(email: "bob@example.com"), "max"),
        };

        IReadOnlyList<string> labels = AccountLabel.Disambiguate(accounts);

        Assert.Equal("Max (Max, alice)", labels[0]);
        Assert.Equal("Max (Max, bob)", labels[1]);
    }

    [Fact]
    public void Disambiguate_SameDomainDifferentPlan_StillUsesThePlan_NotTheDomain()
    {
        var accounts = new[]
        {
            new AccountLabelInput(null, Identity("Acme", "alice@example.com"), "max"),
            new AccountLabelInput(null, Identity("Acme", "bob@example.com"), "team"),
        };

        IReadOnlyList<string> labels = AccountLabel.Disambiguate(accounts);

        Assert.Equal("Acme (Max)", labels[0]);
        Assert.Equal("Acme (Team)", labels[1]);
    }

    [Fact]
    public void Disambiguate_ThreeCollidingAccounts_TwoSharingADomain_DoNotGetPartialDomains()
    {
        // The domain does not tell all three apart, so the whole group uses the old steps.
        var accounts = new[]
        {
            new AccountLabelInput(null, Identity(email: "alice@example.com"), "max"),
            new AccountLabelInput(null, Identity(email: "bob@example.com"), "max"),
            new AccountLabelInput(null, Identity(email: "carol@example.org"), "max"),
        };

        IReadOnlyList<string> labels = AccountLabel.Disambiguate(accounts);

        Assert.Equal(new[] { "Max (Max, alice)", "Max (Max, bob)", "Max (Max, carol)" }, labels);
    }

    [Fact]
    public void Disambiguate_AMemberWithoutAnEmail_FallsBackToTheOldSteps()
    {
        var accounts = new[]
        {
            new AccountLabelInput(null, Identity(email: "alex@example.com"), "max"),
            new AccountLabelInput(null, Identity(email: null), "max"),
        };

        IReadOnlyList<string> labels = AccountLabel.Disambiguate(accounts);

        Assert.Equal(2, labels.Distinct().Count());
        Assert.DoesNotContain("example.com", labels[1]);
    }

    [Fact]
    public void Disambiguate_EachCollidingGroupIsHandledOnItsOwn()
    {
        var accounts = new[]
        {
            new AccountLabelInput(null, Identity(email: "alex@example.com"), "max"),   // group "Max": domains differ
            new AccountLabelInput(null, Identity(email: "alex@example.org"), "max"),
            new AccountLabelInput(null, Identity("Acme", "alice@example.com"), "team"), // group "Acme": same domain
            new AccountLabelInput(null, Identity("Acme", "bob@example.com"), "team"),
            new AccountLabelInput(null, Identity("Solo", "sam@example.net"), "team"),   // unique: untouched
        };

        IReadOnlyList<string> labels = AccountLabel.Disambiguate(accounts);

        Assert.Equal(new[]
        {
            "Max (example.com)", "Max (example.org)",
            "Acme (Team, alice)", "Acme (Team, bob)",
            "Solo",
        }, labels);
    }

    [Fact]
    public void Disambiguate_ASingleAccount_NeverGetsADomain()
    {
        var accounts = new[] { new AccountLabelInput(null, Identity(email: "alex@example.com"), "max") };

        Assert.Equal(new[] { "Max" }, AccountLabel.Disambiguate(accounts));
    }

    [Fact]
    public void Disambiguate_UniqueLabels_NeverGetADomain()
    {
        var accounts = new[]
        {
            new AccountLabelInput(null, Identity("Acme", "alex@example.com"), "team"),
            new AccountLabelInput(null, Identity(null, "alex@example.org"), "max"),
        };

        Assert.Equal(new[] { "Acme", "Max" }, AccountLabel.Disambiguate(accounts));
    }

    [Fact]
    public void Disambiguate_TheUsersOwnOverrides_AreDisambiguatedTheSameWay()
    {
        var accounts = new[]
        {
            new AccountLabelInput("Jobb", Identity(email: "alex@example.com"), "max"),
            new AccountLabelInput("Jobb", Identity(email: "alex@example.org"), "max"),
        };

        Assert.Equal(new[] { "Jobb (example.com)", "Jobb (example.org)" }, AccountLabel.Disambiguate(accounts));
    }

    [Fact]
    public void Disambiguate_ADuplicateRow_DoesNotCountAsACollision_SoNoDomainIsAdded()
    {
        var accounts = new[]
        {
            new AccountLabelInput(null, Identity(email: "alex@example.com"), "max"),
            new AccountLabelInput(null, Identity(email: "alex@example.org"), "max"),
        };

        IReadOnlyList<string> labels = AccountLabel.Disambiguate(accounts, new[] { false, true });

        Assert.Equal("Max", labels[0]);
    }
}
