using ClaudeStatusBar.Ui;
using Xunit;

namespace ClaudeStatusBar.Tests;

/// <summary>
/// The panel header: the title is the account's label; the line under it is the plan and the
/// organisation from Anthropic's own data (PanelText.ComposeAccountSubtitle). Placeholder names only.
/// </summary>
public class PanelHeaderTests
{
    [Fact]
    public void PersonalPlan_WithAUserChosenName_ShowsPlanAndPersonalOrganisation()
    {
        string? subtitle = PanelText.ComposeAccountSubtitle("Privat", "max", "alex@example.com's Organization");

        Assert.Equal("Max · personlig organisation", subtitle);
    }

    [Fact]
    public void TeamPlan_ShowsPlanAndTheOrganisationName()
    {
        Assert.Equal("Team · Acme AB", PanelText.ComposeAccountSubtitle("Jobb", "team", "Acme AB"));
    }

    [Fact]
    public void TheAutoGeneratedPersonalOrganisation_IsNeverShownByName_AndNeverWithTheAddress()
    {
        string? subtitle = PanelText.ComposeAccountSubtitle("Privat", "max", "alex@example.com's Organization");

        Assert.DoesNotContain("example.com", subtitle);
        Assert.DoesNotContain("@", subtitle);
        Assert.DoesNotContain("Organization", subtitle);
    }

    [Fact]
    public void UnknownParts_AreLeftOut()
    {
        Assert.Equal("Team", PanelText.ComposeAccountSubtitle("Jobb", "team", null));
        Assert.Equal("Team", PanelText.ComposeAccountSubtitle("Jobb", "TEAM", "  "));
        Assert.Equal("Acme AB", PanelText.ComposeAccountSubtitle("Jobb", null, "Acme AB"));
        Assert.Null(PanelText.ComposeAccountSubtitle("Jobb", null, null));
        Assert.Null(PanelText.ComposeAccountSubtitle("Jobb", "", ""));
    }

    [Fact]
    public void APartThatJustRepeatsTheTitle_IsLeftOut_AndNothingLeftMeansNoSubtitle()
    {
        // An automatic title that IS the plan: no second "Max".
        Assert.Equal("personlig organisation", PanelText.ComposeAccountSubtitle("Max", "max", "alex@example.com's Organization"));
        // An automatic title that IS the organisation: no second "Acme AB".
        Assert.Equal("Team", PanelText.ComposeAccountSubtitle("Acme AB", "team", "Acme AB"));
        // Everything would repeat: nothing at all.
        Assert.Null(PanelText.ComposeAccountSubtitle("Max", "max", null));
        Assert.Null(PanelText.ComposeAccountSubtitle("acme ab", null, "Acme AB"));
        Assert.Null(PanelText.ComposeAccountSubtitle("Team", "team", "team"));
    }

    [Fact]
    public void TheSubtitle_NeverContainsAnEmailAddress()
    {
        foreach (string? org in new[] { "Acme AB", "alex@example.org's Organization", null })
        {
            string? subtitle = PanelText.ComposeAccountSubtitle("Privat", "max", org);
            if (subtitle is not null) Assert.DoesNotContain("@", subtitle);
        }
    }

    [Fact]
    public void ThePersonalOrganisationWording_IsFixed()
    {
        Assert.Equal("personlig organisation", PanelText.PersonalOrganisation);
    }
}
