using ClaudeStatusBar.Data;

namespace ClaudeStatusBar.Model;

/// <summary>One account's label inputs -- never hardcoded, always the user's own Anthropic data (docs/multi-account.md "Labels").</summary>
public readonly record struct AccountLabelInput(string? OverrideLabel, AccountIdentity? Identity, string? SubscriptionType);

/// <summary>
/// Resolves the display label for one account, then disambiguates duplicates across a whole
/// account set. Rules (docs/multi-account.md "Labels", never hardcoded -- always derived from
/// the user's own accounts.json override or Anthropic account data):
///
///   1. The user's own override from accounts.json.
///   2. oauthAccount.organizationName -- UNLESS it is Anthropic's own auto-generated name for a
///      personal organisation ("&lt;email&gt;'s Organization", see IsAutoGeneratedPersonalOrgName),
///      which is a poor tray label; that case falls through to step 3 instead.
///   3. The plan from subscription_type, title-cased ("Max", "Team", "Enterprise").
///   4. The local part of emailAddress.
///   5. "Konto N".
///
/// If two accounts resolve to the same label, append the plan; if still equal, append the
/// email local part too.
/// </summary>
public static class AccountLabel
{
    const string AutoGeneratedOrgNameSuffix = "'s Organization";

    /// <summary>One account's base label, before the whole-set disambiguation pass.</summary>
    public static string Resolve(AccountLabelInput input, int accountIndex)
    {
        if (!string.IsNullOrWhiteSpace(input.OverrideLabel)) return input.OverrideLabel!.Trim();

        string? orgName = input.Identity?.OrganizationName;
        if (!string.IsNullOrWhiteSpace(orgName) && !IsAutoGeneratedPersonalOrgName(orgName!))
            return orgName!.Trim();

        string? plan = TitleCasePlan(input.SubscriptionType);
        if (plan != null) return plan;

        string? emailLocal = LocalPart(input.Identity?.EmailAddress);
        if (emailLocal != null) return emailLocal;

        return $"Konto {accountIndex + 1}";
    }

    /// <summary>
    /// True for Anthropic's own auto-generated name for a personal (non-Team/Enterprise)
    /// organisation, e.g. "alex@example.com's Organization" -- observed on a real personal
    /// Max login (docs/multi-account.md "Labels"). Using it verbatim as a tray label is worse
    /// than the plan name it stands in for, so Resolve treats it as if organizationName were
    /// absent rather than displaying it.
    /// </summary>
    public static bool IsAutoGeneratedPersonalOrgName(string organizationName) =>
        organizationName.EndsWith(AutoGeneratedOrgNameSuffix, StringComparison.Ordinal);

    /// <summary>"max" -&gt; "Max", "TEAM" -&gt; "Team", "enterprise" -&gt; "Enterprise". Null/blank stays null (nothing to show).</summary>
    public static string? TitleCasePlan(string? subscriptionType)
    {
        if (string.IsNullOrWhiteSpace(subscriptionType)) return null;
        string s = subscriptionType.Trim();
        return char.ToUpperInvariant(s[0]) + s[1..].ToLowerInvariant();
    }

    static string? LocalPart(string? email)
    {
        if (string.IsNullOrWhiteSpace(email)) return null;
        int at = email.IndexOf('@');
        return at > 0 ? email[..at] : email;
    }

    /// <summary>
    /// Whole-set disambiguation pass (docs/multi-account.md): every account's base label is
    /// resolved first; any base label that collides with another account's gets the plan
    /// appended in parentheses; any label still colliding after that (same org, same plan) gets
    /// the email local part appended too. Order is preserved; accounts whose base label was
    /// already unique come back unchanged.
    /// </summary>
    public static IReadOnlyList<string> Disambiguate(IReadOnlyList<AccountLabelInput> accounts)
    {
        int n = accounts.Count;
        var baseLabels = new string[n];
        for (int i = 0; i < n; i++)
            baseLabels[i] = Resolve(accounts[i], i);

        bool[] dup = DuplicateMask(baseLabels);
        if (!Array.Exists(dup, x => x)) return baseLabels;

        var withPlan = new string[n];
        for (int i = 0; i < n; i++)
            withPlan[i] = dup[i] ? Suffix(baseLabels[i], TitleCasePlan(accounts[i].SubscriptionType)) : baseLabels[i];

        bool[] stillDup = DuplicateMask(withPlan);
        if (!Array.Exists(stillDup, x => x)) return withPlan;

        var final = new string[n];
        for (int i = 0; i < n; i++)
        {
            if (!stillDup[i]) { final[i] = withPlan[i]; continue; }

            string? plan = TitleCasePlan(accounts[i].SubscriptionType);
            string? email = LocalPart(accounts[i].Identity?.EmailAddress);
            string clause = plan != null && email != null ? $"{plan}, {email}" : plan ?? email ?? "";
            final[i] = clause.Length == 0 ? baseLabels[i] : Suffix(baseLabels[i], clause);
        }
        return final;
    }

    static string Suffix(string label, string? extra) => string.IsNullOrEmpty(extra) ? label : $"{label} ({extra})";

    static bool[] DuplicateMask(string[] labels)
    {
        var counts = new Dictionary<string, int>(StringComparer.Ordinal);
        foreach (string l in labels) counts[l] = counts.GetValueOrDefault(l) + 1;
        return Array.ConvertAll(labels, l => counts[l] > 1);
    }
}
