using ClaudeStatusBar.Data;

namespace ClaudeStatusBar.Model;

/// <summary>One account's label inputs -- never hardcoded, always the user's own Anthropic data (docs/multi-account.md "Labels").</summary>
public readonly record struct AccountLabelInput(string? OverrideLabel, AccountIdentity? Identity, string? SubscriptionType);

/// <summary>
/// Resolves the display label for one account, then disambiguates duplicates across a whole
/// account set. Rules (docs/multi-account.md "Labels", never hardcoded -- always derived from
/// the user's own accounts.json override or Anthropic account data):
///
///   1. The user's own override from accounts.json.
///   2. oauthAccount.organizationName -- UNLESS it is Anthropic's own auto-generated name for a
///      personal organisation ("&lt;email&gt;'s Organization", see IsAutoGeneratedPersonalOrgName),
///      which is a poor tray label; that case falls through to step 3 instead.
///   3. The plan from subscription_type, title-cased ("Max", "Team", "Enterprise").
///   4. The local part of emailAddress.
///   5. "Konto N".
///
/// If two accounts resolve to the same label: when their email domains tell them apart, append the
/// domain ("Max (example.com)" / "Max (example.org)"); otherwise append the plan; if still equal,
/// append the email local part too. Every part comes from the user's own account data.
/// </summary>
public static class AccountLabel
{
    const string AutoGeneratedOrgNameSuffix = "'s Organization";

    /// <summary>One account's base label, before the whole-set disambiguation pass.</summary>
    public static string Resolve(AccountLabelInput input, int accountIndex)
    {
        if (!string.IsNullOrWhiteSpace(input.OverrideLabel)) return input.OverrideLabel!.Trim();

        string? orgName = input.Identity?.OrganizationName;
        if (!string.IsNullOrWhiteSpace(orgName) && !IsAutoGeneratedPersonalOrgName(orgName!))
            return orgName!.Trim();

        string? plan = TitleCasePlan(input.SubscriptionType);
        if (plan != null) return plan;

        string? emailLocal = LocalPart(input.Identity?.EmailAddress);
        if (emailLocal != null) return emailLocal;

        return $"Konto {accountIndex + 1}";
    }

    /// <summary>
    /// True for Anthropic's own auto-generated name for a personal (non-Team/Enterprise)
    /// organisation, e.g. "alex@example.com's Organization" -- observed on a real personal
    /// Max login (docs/multi-account.md "Labels"). Using it verbatim as a tray label is worse
    /// than the plan name it stands in for, so Resolve treats it as if organizationName were
    /// absent rather than displaying it.
    /// </summary>
    public static bool IsAutoGeneratedPersonalOrgName(string organizationName) =>
        organizationName.EndsWith(AutoGeneratedOrgNameSuffix, StringComparison.Ordinal);

    /// <summary>"max" -&gt; "Max", "TEAM" -&gt; "Team", "enterprise" -&gt; "Enterprise". Null/blank stays null (nothing to show).</summary>
    public static string? TitleCasePlan(string? subscriptionType)
    {
        if (string.IsNullOrWhiteSpace(subscriptionType)) return null;
        string s = subscriptionType.Trim();
        return char.ToUpperInvariant(s[0]) + s[1..].ToLowerInvariant();
    }

    static string? LocalPart(string? email)
    {
        if (string.IsNullOrWhiteSpace(email)) return null;
        int at = email.IndexOf('@');
        return at > 0 ? email[..at] : email;
    }

    /// <summary>
    /// Whole-set disambiguation pass (docs/multi-account.md): every account's base label is
    /// resolved first; any base label that collides with another account's gets, per group of
    /// colliding labels, the email DOMAIN appended in parentheses when every member has one and they
    /// are all different (a Max plan on two different mail domains); a group the domain does not
    /// separate gets the plan appended instead; any label still colliding after that (same org,
    /// same plan, same domain) gets the email local part appended too. Order is preserved; accounts whose base label was
    /// already unique come back unchanged.
    ///
    /// <paramref name="isDuplicate"/> (docs/multi-account.md "Duplicate accounts", Model/
    /// AccountDuplicates.cs): accounts flagged true never participate in the collision counting
    /// in EITHER direction -- they can't collide with anything, and nothing else is considered
    /// colliding with them. This pass exists for DIFFERENT accounts that happen to share a
    /// label, never for two rows tracking the SAME login; a true duplicate's row is replaced
    /// entirely by StatusBarApplicationContext (Ui/PanelText.ComposeDuplicateAccountRow), so its
    /// own returned label here is never actually shown. Null (the default) treats every account
    /// as a normal participant, exactly like before this parameter existed.
    /// </summary>
    public static IReadOnlyList<string> Disambiguate(IReadOnlyList<AccountLabelInput> accounts, IReadOnlyList<bool>? isDuplicate = null)
    {
        int n = accounts.Count;
        var baseLabels = new string[n];
        for (int i = 0; i < n; i++)
            baseLabels[i] = Resolve(accounts[i], i);

        var participates = new bool[n];
        for (int i = 0; i < n; i++) participates[i] = isDuplicate is null || !isDuplicate[i];

        bool[] dup = DuplicateMask(baseLabels, participates);
        if (!Array.Exists(dup, x => x)) return baseLabels;

        // Step 1: the email DOMAIN, per group of colliding labels, but only where it actually tells
        // the group's members apart (every member has a domain and they are all different):
        // "Max (example.com)" / "Max (example.org)". A group whose domains are missing or shared
        // keeps its base label here and goes on to the plan / local-part steps below, as before.
        var current = (string[])baseLabels.Clone();
        foreach (IGrouping<string, int> group in Enumerable.Range(0, n).Where(i => dup[i]).GroupBy(i => baseLabels[i], StringComparer.Ordinal))
        {
            string?[] domains = group.Select(i => EmailDomain(accounts[i].Identity?.EmailAddress)).ToArray();
            bool tellsThemApart = domains.All(d => d != null)
                && domains.Distinct(StringComparer.OrdinalIgnoreCase).Count() == domains.Length;
            if (!tellsThemApart) continue;
            int k = 0;
            foreach (int i in group) current[i] = Suffix(baseLabels[i], domains[k++]);
        }

        bool[] dupAfterDomain = DuplicateMask(current, participates);
        if (!Array.Exists(dupAfterDomain, x => x)) return current;

        // Step 2: the plan.
        var withPlan = new string[n];
        for (int i = 0; i < n; i++)
            withPlan[i] = dupAfterDomain[i] ? Suffix(current[i], TitleCasePlan(accounts[i].SubscriptionType)) : current[i];

        bool[] stillDup = DuplicateMask(withPlan, participates);
        if (!Array.Exists(stillDup, x => x)) return withPlan;

        // Step 3: plan AND email local part (same organisation, same plan, same email domain).
        var final = new string[n];
        for (int i = 0; i < n; i++)
        {
            if (!stillDup[i]) { final[i] = withPlan[i]; continue; }

            string? plan = TitleCasePlan(accounts[i].SubscriptionType);
            string? email = LocalPart(accounts[i].Identity?.EmailAddress);
            string clause = plan != null && email != null ? $"{plan}, {email}" : plan ?? email ?? "";
            final[i] = clause.Length == 0 ? current[i] : Suffix(current[i], clause);
        }
        return final;
    }

    /// <summary>The part of an email address after the last '@', lower-cased; null when there is none.</summary>
    static string? EmailDomain(string? email)
    {
        if (string.IsNullOrWhiteSpace(email)) return null;
        int at = email.LastIndexOf('@');
        return at >= 0 && at < email.Length - 1 ? email[(at + 1)..].Trim().ToLowerInvariant() : null;
    }

    static string Suffix(string label, string? extra) => string.IsNullOrEmpty(extra) ? label : $"{label} ({extra})";

    static bool[] DuplicateMask(string[] labels, bool[] participates)
    {
        var counts = new Dictionary<string, int>(StringComparer.Ordinal);
        for (int i = 0; i < labels.Length; i++)
            if (participates[i]) counts[labels[i]] = counts.GetValueOrDefault(labels[i]) + 1;

        var result = new bool[labels.Length];
        for (int i = 0; i < labels.Length; i++)
            result[i] = participates[i] && counts.GetValueOrDefault(labels[i]) > 1;
        return result;
    }
}
