# Adds a second (or third, ...) Claude account to Claude Status Bar (docs/multi-account.md):
# creates %LOCALAPPDATA%\ClaudeStatusBar\accounts\<n>\config, runs an interactive `claude` login
# pointed at it (CLAUDE_CONFIG_DIR), appends the entry to accounts.json, and restarts the app.
#
# DUPLICATE CHECK (docs/multi-account.md "Duplicate accounts"): after the login, this script
# reads the new directory's accountUuid+organizationUuid and compares it against every already-
# configured account (including the default %USERPROFILE%\.claude.json login when an entry
# follows it). If another entry already tracks that exact identity, nothing is registered -- the
# browser most likely reused an existing claude.ai session instead of letting you pick a
# different account. The new login directory is left on disk either way.
#
#   .\scripts\add-account.ps1                 Add a new account (interactive login)
#   .\scripts\add-account.ps1 -Label "Team"   ...with a display-name override
#   .\scripts\add-account.ps1 -Register <n>   Register a directory that is already logged in
#                                              (recovery if a previous run was interrupted)
#   .\scripts\add-account.ps1 -List           List configured accounts and their slot numbers
#   .\scripts\add-account.ps1 -Remove <n>     Remove account <n> from accounts.json (leaves its
#                                              config directory on disk -- it holds a login)
param(
    [string]$Label,
    [switch]$List,
    [int]$Remove = 0,
    [string]$Register
)

$ErrorActionPreference = 'Stop'

$dataRoot       = Join-Path $env:LOCALAPPDATA 'ClaudeStatusBar'
$accountsRoot   = Join-Path $dataRoot 'accounts'
$accountsJson   = Join-Path $dataRoot 'accounts.json'
$installDir     = Join-Path $env:LOCALAPPDATA 'Programs\ClaudeStatusBar'
$exe            = Join-Path $installDir 'ClaudeStatusBar.exe'
$defaultClaudeDir  = Join-Path $env:USERPROFILE '.claude'
$defaultClaudeJson = Join-Path $env:USERPROFILE '.claude.json'

# ---- identity reading (docs/multi-account.md "Duplicate accounts") ----
#
# Deliberately NOT ConvertFrom-Json: a real .claude.json can contain case-differing duplicate
# keys, and Windows PowerShell 5.1's ConvertFrom-Json throws on that (its backing hashtable is
# case-insensitive) instead of just picking one -- the same reason add-account.sh reads this
# file with its own dedicated parser rather than a generic JSON one. A plain regex scoped to the
# oauthAccount block is good enough for the three fields this script needs.

function Read-Identity([string]$claudeJsonPath) {
    if (-not (Test-Path $claudeJsonPath)) { return $null }
    $raw = Get-Content $claudeJsonPath -Raw
    $oauthMatch = [regex]::Match($raw, '"oauthAccount"\s*:\s*\{')
    if (-not $oauthMatch.Success) { return $null }

    # Scan forward from the oauthAccount key to its matching closing brace, so a same-named field
    # anywhere else in the file (there is none today, but this is cheap insurance) can never be
    # picked up by mistake.
    $start = $oauthMatch.Index + $oauthMatch.Length
    $depth = 1
    $i = $start
    while ($i -lt $raw.Length -and $depth -gt 0) {
        if ($raw[$i] -eq '{') { $depth++ }
        elseif ($raw[$i] -eq '}') { $depth-- }
        $i++
    }
    $block = $raw.Substring($start, [Math]::Max(0, $i - $start - 1))

    $accountUuidMatch = [regex]::Match($block, '"accountUuid"\s*:\s*"([^"]+)"')
    if (-not $accountUuidMatch.Success) { return $null }
    $orgUuidMatch = [regex]::Match($block, '"organizationUuid"\s*:\s*"([^"]+)"')
    $orgNameMatch = [regex]::Match($block, '"organizationName"\s*:\s*"([^"]+)"')

    return [PSCustomObject]@{
        AccountUuid      = $accountUuidMatch.Groups[1].Value
        OrganizationUuid = if ($orgUuidMatch.Success) { $orgUuidMatch.Groups[1].Value } else { $null }
        OrganizationName = if ($orgNameMatch.Success) { $orgNameMatch.Groups[1].Value } else { $null }
    }
}

# Which organization a login landed in, in words the user recognises from claude.ai -- the one
# thing that tells a personal plan and a Team/Enterprise login on the same email apart. The plan
# itself (max, team, ...) only arrives with get_usage, so this script can't show it. Anthropic's
# auto-generated "<email>'s Organization" is the personal one (AccountLabel.IsAutoGeneratedPersonalOrgName).
function Format-Organization($identity) {
    $name = if ($identity) { $identity.OrganizationName } else { $null }
    if ([string]::IsNullOrWhiteSpace($name)) { return 'an unnamed organization' }
    if ($name.EndsWith("'s Organization")) { return 'your personal organization' }
    return "the organization `"$name`""
}

# Mirrors AccountIdentity.StateKey (docs/multi-account.md "Identity guard"): accountUuid alone
# identifies the PERSON, not the plan, so accountUuid+organizationUuid is the actual identity.
function Get-StateKey($identity) {
    if (-not $identity) { return $null }
    if ($identity.OrganizationUuid) { return "$($identity.AccountUuid)_$($identity.OrganizationUuid)" }
    return $identity.AccountUuid
}

# Where Claude Code itself keeps one account entry's identity file: the DEFAULT entry
# (configDir null) reads %USERPROFILE%\.claude.json (a SIBLING of %USERPROFILE%\.claude, not
# inside it -- verified on a real installation, see docs/multi-account.md), every other entry
# reads <configDir>\.claude.json.
function Get-IdentityFilePath([string]$configDir) {
    if ([string]::IsNullOrEmpty($configDir)) { return $defaultClaudeJson }
    return Join-Path $configDir '.claude.json'
}

# Does any OTHER configured account already track this identity? Returns the matching account's
# [index, slot label], or $null. $excludeConfigDir lets a re-registration check skip comparing a
# directory against itself.
function Find-DuplicateAccount($config, [string]$stateKey, $excludeConfigDir) {
    if (-not $stateKey) { return $null }
    $i = 0
    foreach ($acct in $config.accounts) {
        if ($acct.configDir -ne $excludeConfigDir) {
            $existingKey = Get-StateKey (Read-Identity (Get-IdentityFilePath $acct.configDir))
            if ($existingKey -and $existingKey -eq $stateKey) {
                $slot = if ([string]::IsNullOrEmpty($acct.configDir)) { 'default' } else { Get-SlotNumber $acct.configDir }
                return [PSCustomObject]@{ Index = $i; Slot = $slot }
            }
        }
        $i++
    }
    return $null
}

function Get-AccountsConfig {
    if (-not (Test-Path $accountsJson)) {
        # Mirrors Config/AccountsConfig.cs's Default(): the app creates this file itself on
        # first run too, so this only matters if the script runs before the app ever has.
        return [PSCustomObject]@{
            displayMode = 'perAccount'
            maxIcons    = 3
            accounts    = @([PSCustomObject]@{ configDir = $null; label = $null; enabled = $true })
        }
    }
    return Get-Content $accountsJson -Raw | ConvertFrom-Json
}

function Save-AccountsConfig($config) {
    New-Item -ItemType Directory -Force -Path $dataRoot | Out-Null
    $json = $config | ConvertTo-Json -Depth 6
    $tmp = "$accountsJson.tmp"
    Set-Content -Path $tmp -Value $json -Encoding utf8
    Move-Item -Path $tmp -Destination $accountsJson -Force
}

# Slot number from a configDir like "...\accounts\<n>\config" -- the on-disk numbering this
# script owns; accounts.json itself has no separate "n" field, only the path.
function Get-SlotNumber([string]$configDir) {
    if ([string]::IsNullOrEmpty($configDir)) { return $null }
    if ($configDir -match '[\\/]accounts[\\/](\d+)[\\/]config$') { return [int]$Matches[1] }
    return $null
}

function Restart-StatusBar {
    Get-Process ClaudeStatusBar -ErrorAction SilentlyContinue | ForEach-Object {
        $_.Kill()
        $_.WaitForExit(5000) | Out-Null
    }
    if (Test-Path $exe) {
        Start-Process $exe
        Write-Host "Restarted: $exe"
    } else {
        Write-Host "Not installed yet -- run .\scripts\install.ps1 to start it with the new account list."
    }
}

# ---- -List ----

if ($List) {
    $config = Get-AccountsConfig
    Write-Host "Display mode: $($config.displayMode)   Max icons: $($config.maxIcons)"
    Write-Host ''
    $i = 0
    foreach ($acct in $config.accounts) {
        $slot = if ([string]::IsNullOrEmpty($acct.configDir)) { 'default' } else { Get-SlotNumber $acct.configDir }
        $label = if ($acct.label) { $acct.label } else { '(auto)' }
        $state = if ($acct.enabled) { 'enabled' } else { 'disabled' }
        Write-Host ("  [{0}] slot={1,-8} label={2,-16} {3}" -f $i, $slot, $label, $state)
        $i++
    }
    return
}

# ---- -Remove <n> ----

if ($Remove -gt 0) {
    $config = Get-AccountsConfig
    $target = $config.accounts | Where-Object { (Get-SlotNumber $_.configDir) -eq $Remove }
    if (-not $target) {
        Write-Host "No account with slot $Remove found. Run -List to see configured accounts." -ForegroundColor Yellow
        return
    }
    $config.accounts = @($config.accounts | Where-Object { $_ -ne $target })
    Save-AccountsConfig $config
    Write-Host "Removed account slot $Remove from accounts.json."
    Write-Host "Its login is untouched on disk at: $(Join-Path $accountsRoot "$Remove\config") -- delete that folder yourself if you no longer want it."
    Restart-StatusBar
    return
}

# ---- -Register (recovery: a config directory that is already logged in) ----

if ($Register -and -not $List -and $Remove -le 0) {
    $dir = if (Test-Path $Register) { (Resolve-Path $Register).Path } else { Join-Path $accountsRoot ($Register + "\config") }
    if (-not (Test-Path (Join-Path $dir ".claude.json"))) {
        Write-Host "No login found in $dir -- nothing to register." -ForegroundColor Yellow
        return
    }
    $newIdentity = Read-Identity (Join-Path $dir ".claude.json")
    if (-not $newIdentity) {
        Write-Host "No oauthAccount found in $dir -- the login did not take. Nothing was registered." -ForegroundColor Yellow
        return
    }

    $config = Get-AccountsConfig
    if (@($config.accounts) | Where-Object { $_.configDir -eq $dir }) {
        Write-Host "$dir is already registered."
        return
    }

    # docs/multi-account.md "Duplicate accounts": a directory that is logged in doesn't
    # necessarily mean it holds a DIFFERENT account -- the browser can reuse an existing
    # claude.ai session instead of letting the user pick another one.
    $dup = Find-DuplicateAccount $config (Get-StateKey $newIdentity) $dir
    if ($dup) {
        Write-Host ""
        Write-Host "This login ($(Format-Organization $newIdentity)) is already tracked as account [$($dup.Index)] (slot $($dup.Slot)) -- not registering a duplicate." -ForegroundColor Yellow
        Write-Host "Your browser probably reused an existing claude.ai session instead of letting you choose a"
        Write-Host "different account or organization. Log in with the other one in $dir (open a private/incognito"
        Write-Host "browser window, or sign out of claude.ai first), then re-run this command."
        return
    }

    $config.accounts = @($config.accounts) + [PSCustomObject]@{ configDir = $dir; label = $null; enabled = $true }
    Save-AccountsConfig $config
    Write-Host "Logged in to $(Format-Organization $newIdentity)."
    Write-Host "Registered $dir."
    Restart-StatusBar
    return
}

# ---- add a new account ----

New-Item -ItemType Directory -Force -Path $accountsRoot | Out-Null
$slot = 1
while (Test-Path (Join-Path $accountsRoot "$slot\config")) { $slot++ }
$configDir = Join-Path $accountsRoot "$slot\config"
New-Item -ItemType Directory -Force -Path $configDir | Out-Null

Write-Host "About to log into a NEW Claude account."
Write-Host "This runs 'claude' with CLAUDE_CONFIG_DIR pointed at a fresh, empty directory:"
Write-Host "  $configDir"
Write-Host "A browser window will open for you to log in. If your login belongs to more than one"
Write-Host "organization (say a personal plan and a Team), choose the one you want there."
Write-Host "When the login is done, leave Claude Code with /exit so this script can finish and"
Write-Host "save the account."
Write-Host "Do NOT press Ctrl+C -- that kills this script too, and the account is not saved."
Write-Host "If that happens anyway, re-run with:  -Register $slot"
Write-Host ''

$env:CLAUDE_CONFIG_DIR = $configDir
try {
    & claude
} finally {
    Remove-Item Env:\CLAUDE_CONFIG_DIR -ErrorAction SilentlyContinue
}

$identityFile = Join-Path $configDir '.claude.json'
if (-not (Test-Path $identityFile)) {
    Write-Host "No login was detected at $identityFile -- the account was not added. Re-run this script to try again." -ForegroundColor Yellow
    return
}

$newIdentity = Read-Identity $identityFile
if (-not $newIdentity) {
    Write-Host "No oauthAccount found at $identityFile -- the login did not take. Re-run this script to try again." -ForegroundColor Yellow
    return
}

$config = Get-AccountsConfig

# docs/multi-account.md "Duplicate accounts": also checks the default login
# (%USERPROFILE%\.claude.json) via Find-DuplicateAccount/Get-IdentityFilePath whenever an
# existing entry follows it (configDir null) -- the same login can just as easily collide with
# "whatever you're logged into" as with another scripted slot.
$dup = Find-DuplicateAccount $config (Get-StateKey $newIdentity) $configDir
if ($dup) {
    Write-Host ""
    Write-Host "You logged in to $(Format-Organization $newIdentity), which is the SAME login as account [$($dup.Index)] (slot $($dup.Slot)) -- not adding it as a new account." -ForegroundColor Yellow
    Write-Host "Your browser probably reused an existing claude.ai session instead of letting you choose a"
    Write-Host "different account or organization. Nothing was registered, but the new login directory is left on disk at:"
    Write-Host "  $configDir"
    Write-Host ""
    Write-Host "To track a genuinely different account there:"
    Write-Host "  1. Open a private/incognito browser window (or sign out of claude.ai first)."
    Write-Host "  2. Log into that directory directly:"
    Write-Host "       `$env:CLAUDE_CONFIG_DIR = `"$configDir`""
    Write-Host "       claude"
    Write-Host "     ...then /login inside Claude Code, choosing the other account or organization, then /exit."
    Write-Host "  3. Register it:"
    Write-Host "       .\scripts\add-account.ps1 -Register $slot"
    return
}

$config.accounts = @($config.accounts) + [PSCustomObject]@{
    configDir = $configDir
    label     = if ($Label) { $Label } else { $null }
    enabled   = $true
}
Save-AccountsConfig $config

Write-Host "Logged in to $(Format-Organization $newIdentity)."
Write-Host "Added account slot $slot ($configDir) to accounts.json."
Restart-StatusBar
